import React,{useEffect,useState} from 'react';
import {useRpc} from '@get-bb/plugin-sdk/app';
import {connectionsContract,type Connection} from './connections-contract.js';
import {Button} from './components/ui/button.js';
import {Input} from './components/ui/input.js';
const blank=():Connection=>({id:crypto.randomUUID(),name:'',protocol:'ftps',hostname:'',port:21,username:'',root:'/',enabled:true});
export function ConnectionSettings(){
 const rpc=useRpc<typeof connectionsContract>();const [items,setItems]=useState<(Connection&{hasPassword:boolean})[]>([]);const [editing,setEditing]=useState<Connection|null>(null);const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 async function load(){setItems(await rpc.call('connections',null));}
 useEffect(()=>{void load().catch(e=>setError(String(e)));},[]);
 async function run(action:()=>Promise<unknown>){setBusy(true);setError('');setMessage('');try{await action();await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 function field<K extends keyof Connection>(key:K,value:Connection[K]){setEditing(c=>c?{...c,[key]:value}:c);}
 return <div className="space-y-3" aria-label="Внешние подключения"><p className="text-sm text-muted-foreground">Подключите сайт по FTP, FTPS или SFTP. Он появится рядом с машинами в панели «Файлы подключений». Доступ — просмотр и скачивание.</p>{items.map(c=><div key={c.id} className="flex flex-wrap items-center gap-2 rounded-lg border border-border p-3"><div className="min-w-0 flex-1"><div className="text-sm font-medium">{c.name}</div><div className="break-all text-xs text-muted-foreground">{c.protocol.toUpperCase()} · {c.hostname}:{c.port} · {c.root} · {c.enabled?'Включено':'Выключено'}</div></div><Button size="sm" variant="outline" disabled={busy||!c.enabled} onClick={()=>void run(async()=>{await rpc.call('testConnection',{id:c.id});setMessage(`Подключение «${c.name}» работает`);})}>Проверить</Button><Button size="sm" variant="ghost" disabled={busy} onClick={()=>{const {hasPassword,...connection}=c;setEditing(connection);setPassword('');}}>Изменить</Button><Button size="sm" variant="ghost" disabled={busy} onClick={()=>void run(()=>rpc.call('removeConnection',{id:c.id}))}>Удалить</Button></div>)}
 {!editing?<Button size="sm" variant="outline" onClick={()=>{setEditing(blank());setPassword('');}}>Добавить подключение</Button>:<form className="space-y-3 rounded-lg border border-border p-4" onSubmit={e=>{e.preventDefault();void run(async()=>{await rpc.call('saveConnection',{connection:editing,...(password?{password}:{})});setEditing(null);setPassword('');setMessage('Подключение сохранено');});}}>
 <label className="block text-sm">Название<Input required value={editing.name} onChange={e=>field('name',e.target.value)} placeholder="Мой сайт"/></label>
 <label className="block text-sm">Протокол<select className="mt-1 block w-full rounded-md border border-border bg-background p-2" value={editing.protocol} onChange={e=>{const protocol=e.target.value as Connection['protocol'];setEditing(c=>c?{...c,protocol,port:protocol==='sftp'?22:21}:c);}}><option value="ftps">FTPS — FTP с TLS</option><option value="sftp">SFTP — SSH</option><option value="ftp">FTP — без шифрования</option></select></label>
 <div className="flex gap-2"><label className="min-w-0 flex-1 text-sm">Адрес сервера<Input required value={editing.hostname} onChange={e=>field('hostname',e.target.value)} placeholder="ftp.example.com"/></label><label className="w-24 text-sm">Порт<Input required type="number" min={1} max={65535} value={editing.port} onChange={e=>field('port',Number(e.target.value))}/></label></div>
 <label className="block text-sm">Логин<Input required autoComplete="off" value={editing.username} onChange={e=>field('username',e.target.value)}/></label>
 <label className="block text-sm">Пароль<Input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder={items.some(c=>c.id===editing.id&&c.hasPassword)?'Оставьте пустым, чтобы сохранить пароль':'Пароль подключения'}/></label>
 <label className="block text-sm">Доступная папка<Input required value={editing.root} onChange={e=>field('root',e.target.value)} placeholder="/public_html"/></label>
 {editing.protocol==='sftp'&&<label className="block text-sm">SHA-256 ключа сервера (64 hex-символа)<Input required pattern="[a-fA-F0-9]{64}" value={editing.fingerprint??''} onChange={e=>field('fingerprint',e.target.value)}/><span className="text-xs text-muted-foreground">Отпечаток из панели хостинга или от администратора сервера.</span></label>}
 <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={editing.enabled} onChange={e=>field('enabled',e.target.checked)}/>Доступ включён</label>
 <p className="text-xs text-muted-foreground">Соединение устанавливает основной сервер BB. Пароль хранится в штатном секретном хранилище BB и не передаётся агентам.</p>
 <div className="flex gap-2"><Button size="sm" disabled={busy}>Сохранить</Button><Button type="button" size="sm" variant="ghost" disabled={busy} onClick={()=>{setEditing(null);setPassword('');}}>Отмена</Button></div></form>}
 {error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{message&&<p role="status" className="text-sm text-muted-foreground">{message}</p>}</div>;
}
