import React,{useEffect,useState} from 'react';
import {useRpc} from '@get-bb/plugin-sdk/app';
import {connectionsContract,type Connection} from './connections-contract.js';
import {Button} from './components/ui/button.js';
import {Input} from './components/ui/input.js';
const blank=():Connection=>({id:crypto.randomUUID(),name:'',protocol:'ftps',hostname:'',port:21,username:'',root:'/',enabled:true});
export function ConnectionSettings(){
 const rpc=useRpc<typeof connectionsContract>();const [items,setItems]=useState<(Connection&{hasPassword:boolean})[]>([]);const [editing,setEditing]=useState<Connection|null>(null);const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 async function load(){setItems(await rpc.call('connections',null));}
 useEffect(()=>{void load().catch(e=>setError(String(e)));},[]);
 async function run(action:()=>Promise<unknown>){setBusy(true);setError('');setMessage('');try{await action();await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 function field<K extends keyof Connection>(key:K,value:Connection[K]){setEditing(c=>c?{...c,[key]:value}:c);}
 return <div className="space-y-3" aria-label="External connections"><p className="text-sm text-muted-foreground">Connect a website using FTP, FTPS or SFTP. It will appear alongside your machines in Connected Files. Access is read-only: browse and download.</p>{items.map(c=><div key={c.id} className="flex flex-wrap items-center gap-2 rounded-lg border border-border p-3"><div className="min-w-0 flex-1"><div className="text-sm font-medium">{c.name}</div><div className="break-all text-xs text-muted-foreground">{c.protocol.toUpperCase()} · {c.hostname}:{c.port} · {c.root} · {c.enabled?'Enabled':'Off'}</div></div><Button size="sm" variant="outline" disabled={busy||!c.enabled} onClick={()=>void run(async()=>{await rpc.call('testConnection',{id:c.id});setMessage(`Connection “${c.name}” is working`);})}>Test connection</Button><Button size="sm" variant="ghost" disabled={busy} onClick={()=>{const {hasPassword,...connection}=c;setEditing(connection);setPassword('');}}>Edit</Button><Button size="sm" variant="ghost" disabled={busy} onClick={()=>void run(()=>rpc.call('removeConnection',{id:c.id}))}>Delete</Button></div>)}
 {!editing?<Button size="sm" variant="outline" onClick={()=>{setEditing(blank());setPassword('');}}>Add connection</Button>:<form className="space-y-3 rounded-lg border border-border p-4" onSubmit={e=>{e.preventDefault();void run(async()=>{await rpc.call('saveConnection',{connection:editing,...(password?{password}:{})});setEditing(null);setPassword('');setMessage('Connection saved');});}}>
 <label className="block text-sm">Name<Input required value={editing.name} onChange={e=>field('name',e.target.value)} placeholder="My website"/></label>
 <label className="block text-sm">Protocol<select className="mt-1 block w-full rounded-md border border-border bg-background p-2" value={editing.protocol} onChange={e=>{const protocol=e.target.value as Connection['protocol'];setEditing(c=>c?{...c,protocol,port:protocol==='sftp'?22:21}:c);}}><option value="ftps">FTPS — FTP over TLS</option><option value="sftp">SFTP — SSH</option><option value="ftp">FTP — unencrypted</option></select></label>
 <div className="flex gap-2"><label className="min-w-0 flex-1 text-sm">Server address<Input required value={editing.hostname} onChange={e=>field('hostname',e.target.value)} placeholder="ftp.example.com"/></label><label className="w-24 text-sm">Port<Input required type="number" min={1} max={65535} value={editing.port} onChange={e=>field('port',Number(e.target.value))}/></label></div>
 <label className="block text-sm">Username<Input required autoComplete="off" value={editing.username} onChange={e=>field('username',e.target.value)}/></label>
 <label className="block text-sm">Password<Input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder={items.some(c=>c.id===editing.id&&c.hasPassword)?'Leave blank to keep the current password':'Connection password'}/></label>
 <label className="block text-sm">Accessible folder<Input required value={editing.root} onChange={e=>field('root',e.target.value)} placeholder="/public_html"/></label>
 {editing.protocol==='sftp'&&<label className="block text-sm">Server host key SHA-256 (64 hex characters)<Input required pattern="[a-fA-F0-9]{64}" value={editing.fingerprint??''} onChange={e=>field('fingerprint',e.target.value)}/><span className="text-xs text-muted-foreground">Get the fingerprint from your hosting dashboard or server administrator.</span></label>}
 <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={editing.enabled} onChange={e=>field('enabled',e.target.checked)}/>Access enabled</label>
 <p className="text-xs text-muted-foreground">Connections originate from the main BB server. Passwords are stored in BB’s secret storage and are not shared with agents.</p>
 <div className="flex gap-2"><Button size="sm" disabled={busy}>Save</Button><Button type="button" size="sm" variant="ghost" disabled={busy} onClick={()=>{setEditing(null);setPassword('');}}>Cancel</Button></div></form>}
 {error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{message&&<p role="status" className="text-sm text-muted-foreground">{message}</p>}</div>;
}
